reading-returners:
  component: '@sls-next/serverless-component@1.19.0'
  inputs:
    bucketName: reading-returners-bucket
    bucketRegion: eu-west-2
    logLambdaExecutionTimes: true
    name:
      defaultLambda: readingReturnersDefault
      apiLambda: readingReturnersApi
      imageLambda: readingReturnersImage
